apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: compose-flask-app # Build and push this image to a container registry
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service # Service name for MySQL
        - name: MYSQL_PORT
          value: "3306" # MySQL port
        - name: MYSQL_USER
          value: root # MySQL user
        - name: MYSQL_PASSWORD
          value: rootpass # MySQL password
        - name: MYSQL_DATABASE
          value: demo # MySQL database name
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      #   volumeMounts:
      #   - mountPath: /app
      #     name: app-code
      # volumes:
      # - name: app-code
      #   hostPath:
      #     path: /app # This needs to be adjusted based on your Kubernetes host configuration
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app
