apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask # Build and push this image from compose directory "docker build -t flask ." and then "minikube cache add flask:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service # Service name for MySQL
        - name: MYSQL_PORT
          value: "3306" # MySQL port
        - name: MYSQL_USER
          value: root # MySQL user
        - name: MYSQL_PASSWORD
          value: rootpass # MySQL password
        - name: MYSQL_DATABASE
          value: demo # MySQL database name
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app
