apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: memory-hpa-test
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memory-hpa-test
  minReplicas: 1
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 5
        type: Percent
        value: 100
      selectPolicy: Max
    scaleUp:
      policies:
      # - periodSeconds: 5
      #   type: Pods
      #   value: 10
      - periodSeconds: 5
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 5
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85 # Target CPU utilization percentage
