apiVersion: v1
kind: Namespace
metadata:
  name: stress-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hpa-test
  namespace: stress-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: memory-hpa-test
  template:
    metadata:
      labels:
        app: memory-hpa-test
    spec:
      containers:
      - name: pod-stress-test
        image: polinux/stress-ng
        command: [ "/bin/sh", "-c" ]
        #args: ["stress-ng --cpu 4 --vm 1 --vm-bytes 128M --io 4 --timeout 300s"] #MEMORY AND CPU
        #args: ["stress-ng --cpu 10 --timeout 300s"] #ONLY CPU
        args: [ "stress-ng --vm 1 --vm-bytes 128M --io 4 --timeout 300s" ] #ONLY MEMORY
        resources:
          requests:
            memory: "128Mi" # Minimum memory request
            cpu: "500m" # Minimum CPU request
          limits:
            memory: "500Mi" # Maximum memory limit IF WE DISABLE THIS->OOMKilled
            cpu: "1000m" # Maximum CPU limit
---
apiVersion: v1
kind: Service
metadata:
  name: memory-hpa-test-service
  namespace: stress-test
spec:
  selector:
    app: memory-hpa-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
