####
#minikube addons enable metrics-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hpa-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hpa-test
  template:
    metadata:
      labels:
        app: memory-hpa-test
    spec:
      containers:
      - name: pod-stress-test
        image: polinux/stress-ng
        command: [ "/bin/sh", "-c" ]
        args: [ "stress-ng --cpu 1 --cpu-load 5 --timeout 300s" ]
        #args: [ "stress-ng --cpu 10 --cpu-load 15 --timeout 300s" ] BUMP CPU
        resources:
          requests:
            memory: "64Mi" # Minimum memory request
            cpu: "250m" # Minimum CPU request
          limits:
            memory: "512Mi" # Maximum memory limit IF WE DISABLE THIS->OOMKilled
            cpu: "400m" # Maximum CPU limit
